version: "3.9"
services:  
  flask-app:
    container_name: flask-app
    depends_on:
      - postgres-db
    build: 
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - ${FLASK_RUN_PORT}:${FLASK_RUN_PORT}
    volumes:
      - .:/app
  postgres-db:
    container_name: postgres-db
    image: postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres-db-data:/var/lib/postgresql/data
  
volumes:
  postgres-db-data:
